// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADmDW73vJ_9BciHoZnZv7jPX4RuHgCAkE',
    appId: '1:511232090158:web:40b92428030e67bdf43fbf',
    messagingSenderId: '511232090158',
    projectId: 'fixitnow-f2a63',
    authDomain: 'fixitnow-f2a63.firebaseapp.com',
    storageBucket: 'fixitnow-f2a63.appspot.com',
    measurementId: 'G-H3KZBZK1ZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeml0Wx9kRNSk74CVnM9Y0cKAZCnVQj6c',
    appId: '1:511232090158:android:4c06ca858f58b039f43fbf',
    messagingSenderId: '511232090158',
    projectId: 'fixitnow-f2a63',
    storageBucket: 'fixitnow-f2a63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9ePBHIFN2CWPWd3BeZjQ6hfxn5mFnZ8s',
    appId: '1:511232090158:ios:5180607620ad999cf43fbf',
    messagingSenderId: '511232090158',
    projectId: 'fixitnow-f2a63',
    storageBucket: 'fixitnow-f2a63.appspot.com',
    iosClientId: '511232090158-ds34c9gl3h2o21rab5mhos27ktphj52q.apps.googleusercontent.com',
    iosBundleId: 'com.example.tes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9ePBHIFN2CWPWd3BeZjQ6hfxn5mFnZ8s',
    appId: '1:511232090158:ios:5180607620ad999cf43fbf',
    messagingSenderId: '511232090158',
    projectId: 'fixitnow-f2a63',
    storageBucket: 'fixitnow-f2a63.appspot.com',
    iosClientId: '511232090158-ds34c9gl3h2o21rab5mhos27ktphj52q.apps.googleusercontent.com',
    iosBundleId: 'com.example.tes',
  );
}
